### ISSUE TITLE
Duplicate regions!

### ISSUE THREAD

**Issue by vrozaev** [futurecolors/django-geoip#42]
In
django-geoip / django_geoip / management / ipgeobase.py

136 Region.objects.get(name=entry['region__name'])

it can be more than 1 region with this name!

(Mayby its  ipgeobase.ru problem)

**Comment by coagulant** [comment]
Hi!

Is this issue invalid, or is there problem with ipgeobase?

**Comment by vrozaev** [comment]
Problem with ipgeobase:
some Ukraine and Russian regions have identical names.

Do you speak russian? My english bad as it possible.

**Comment by coagulant** [comment]
Можно по-русски. Нужно добавить в get фильтр по региону

**Comment by vrozaev** [comment]
У себя я уже проблему решил, просто Вам сообщаю что она есть.

**Comment by z0rr0** [comment]
Привет.
Я получаю эту же ошибку при периодическом обновлении базы данных, причем появилось это недавно. Подскажите пожалуйста, как можно решить эту проблему?

```
[2015-01-20 18:02:13,604: INFO/MainProcess] Received task: general.tasks.update_geoip[d6c0a299-ee6b-46d1-aee5-6079f3c4f4b6]
[2015-01-20 18:02:13,670: INFO/Worker-3] Removing obsolete geoip from database...
[2015-01-20 18:02:16,506: INFO/Worker-3] Downloading zipfile from ipgeobase.ru...
[2015-01-20 18:02:16,538: INFO/Worker-3] Starting new HTTP connection (1): ipgeobase.ru
[2015-01-20 18:02:25,840: INFO/Worker-3] Extracting files...
[2015-01-20 18:02:38,446: INFO/Worker-3] Updating locations...
[2015-01-20 18:02:40,133: ERROR/MainProcess] Task general.tasks.update_geoip[d6c0a299-ee6b-46d1-aee5-6079f3c4f4b6] raised unexpected: MultipleObjectsReturned('get() returned more than one Region -- it returned 2!',)
Traceback (most recent call last):
  File "/var/project/env/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/project/env/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/project/credmark/general/tasks.py", line 18, in update_geoip
    backend.sync_database()
  File "/var/project/env/lib/python3.4/site-packages/django_geoip/management/ipgeobase.py", line 46, in sync_database
    city_info['cities'])
  File "/var/project/env/lib/python3.4/site-packages/django_geoip/management/ipgeobase.py", line 136, in _update_geography
    region = Region.objects.get(name=entry['region__name'])
  File "/var/project/env/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/project/env/lib/python3.4/site-packages/django/db/models/query.py", line 361, in get
    num if num <= MAX_GET_RESULTS else 'more than %s' % MAX_GET_RESULTS
django_geoip.models.MultipleObjectsReturned: get() returned more than one Region -- it returned 2!
```

**Comment by coagulant** [comment]
Что, если в `region = Region.objects.get(name=entry['region__name'])` добавить фильтр по стране?

**Comment by z0rr0** [comment]
Спасибо, это помогло.

**Comment by coagulant** [comment]
Fixed in #46
