### ISSUE TITLE
Ошибка в Django 1.7.2 python manage.py geoip_update

### ISSUE THREAD

**Issue by semernyakov** [futurecolors/django-geoip#45]
'''
$ python manage.py geoip_update
Downloading zipfile from ipgeobase.ru...
Extracting files...
Updating locations...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(_args, *_options)
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django_geoip/management/commands/geoip_update.py", line 40, in handle
    backend.sync_database()
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django_geoip/management/ipgeobase.py", line 46, in sync_database
    city_info['cities'])
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django_geoip/management/ipgeobase.py", line 136, in _update_geography
    region = Region.objects.get(name=entry['region__name'])
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "/home/beatum/charm/quickproject/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 361, in get
    num if num <= MAX_GET_RESULTS else 'more than %s' % MAX_GET_RESULTS
django_geoip.models.MultipleObjectsReturned: get() returned more than one Region -- it returned 2
'''

**Comment by 124bit** [comment]
+1
because of Krim region x2

**Comment by coagulant** [comment]
Should be fixed in 3f4c5884e32aa0de65a75f4bcd3e2cdeef02a0eb. Could you please test if the fix helps?

**Comment by 124bit** [comment]
sorry, I can't check in near future

**Comment by ecugol** [comment]
@coagulant Works now, i tested latest code from dev.
