### ISSUE TITLE
Ошибка при выполнении geoip_update / Error with run geoip_update command

### ISSUE THREAD

**Issue by aderugin** [futurecolors/django-geoip#47]
При выполнении обновления регионов (первичного), если не определять настройку IPGEOBASE_ALLOWED_COUNTRIES, вылетает следующая ошибка:

```
Downloading zipfile from ipgeobase.ru...
Extracting files...
Updating locations...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django_geoip/management/commands/geoip_update.py", line 40, in handle
    backend.sync_database()
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django_geoip/management/ipgeobase.py", line 46, in sync_database
    city_info['cities'])
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django_geoip/management/ipgeobase.py", line 136, in _update_geography
    region = Region.objects.get(name=entry['region__name'])
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/admin/Sites/django/flowers/.venv/lib/python2.7/site-packages/django/db/models/query.py", line 361, in get
    num if num <= MAX_GET_RESULTS else 'more than %s' % MAX_GET_RESULTS
django_geoip.models.MultipleObjectsReturned: get() returned more than one Region -- it returned 2!
```

Если указать страну (IPGEOBASE_ALLOWED_COUNTRIES = ['RU']), то все отрабатывает без ошибок. Видимо есть одинаковые названия регионов.

На всякий случай прилагаю виртуальное окружение

```
DAWG-Python==0.7.1
Django==1.7.4
MySQL-python==1.2.5
Pillow==2.7.0
Unidecode==0.04.17
django-appconf==0.6
django-debug-toolbar==1.2.2
django-geoip==0.5.1
django-grappelli==2.6.3
docopt==0.6.2
easy-thumbnails==2.2
gunicorn==19.2.0
pymorphy2==0.8
pymorphy2-dicts==2.4.393442.3710985
python-slugify==0.1.0
requests==2.5.1
six==1.9.0
sqlparse==0.1.14
wsgiref==0.1.2
```

**Comment by coagulant** [comment]
Fixed in #46

**Comment by coagulant** [comment]
We released 0.5.2 version with this fix
