### ISSUE TITLE
Error on 'geoip_update'

### ISSUE THREAD

**Issue by MrYoda** [futurecolors/django-geoip#51]
Хотел переехать на свежую версию с 0.4, и поймал такую вот ошибку, даже предположить не могу, из-за чего могло возникнуть. В сентябре 2014го было все нормально, тогда я последний раз обновлял БД ipgeobase.
VirtualBox vagrant instance (1core, RAM 369mb, SWAP 461mb), py3.4, django 1.7, django-geoip 0.5.2, PosgtreSQL 9.4

```
vagrant@debian8:/vagrant/src$ python3 manage.py geoip_update
Downloading zipfile from ipgeobase.ru...
INFO Downloading zipfile from ipgeobase.ru...
DEBUG Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0)
INFO Starting new HTTP connection (1): ipgeobase.ru
DEBUG "GET /files/db/Main/geo_files.zip HTTP/1.1" 200 2313639
Extracting files...
INFO Extracting files...
Updating locations...
INFO Updating locations...
Updating CIDR...
INFO Updating CIDR...
100% |##########################################################################################################################################################################################################|
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.DatabaseError: SSL SYSCALL error: EOF detected


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django_geoip/management/commands/geoip_update.py", line 40, in handle
    backend.sync_database()
  File "/usr/local/lib/python3.4/dist-packages/django_geoip/management/ipgeobase.py", line 49, in sync_database
    self._update_cidr(cidr_info)
  File "/usr/local/lib/python3.4/dist-packages/django_geoip/management/ipgeobase.py", line 163, in _update_cidr
    IpRange.objects.bulk_create(new_ip_ranges)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 409, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 938, in _batched_insert
    using=self.db)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 549, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DatabaseError: SSL SYSCALL error: EOF detected

```

**Comment by coagulant** [comment]
How is that related to library?
