### ISSUE TITLE
"psycopg2.DatabaseError: SSL SYSCALL error: EOF detected" when running geoip_update

### ISSUE THREAD

**Issue by nazariyg** [futurecolors/django-geoip#57]
Followed the installation instructions, migrated the PostgreSQL 9.3 database (wasn't causing any problems previously), but running `python manage.py geoip_update` repeatedly results into:

```
Downloading zipfile from ipgeobase.ru...
Extracting files...
Updating locations...
Updating CIDR...
100% |#########################################################################|
Traceback (most recent call last):
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DatabaseError: SSL SYSCALL error: EOF detected


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django_geoip/management/commands/geoip_update.py", line 40, in handle
    backend.sync_database()
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django_geoip/management/ipgeobase.py", line 49, in sync_database
    self._update_cidr(cidr_info)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django_geoip/management/ipgeobase.py", line 163, in _update_cidr
    IpRange.objects.bulk_create(new_ip_ranges)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/models/query.py", line 392, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/models/query.py", line 937, in _batched_insert
    using=self.db)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 963, in execute_sql
    cursor.execute(sql, params)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/nazariyg/proj/proj_venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DatabaseError: SSL SYSCALL error: EOF detected

coverage==3.7.1
Django==1.8
django-appconf==1.0.1
django-braces==1.8.1
django-debug-toolbar==1.3.2
django-extensions==1.5.6
django-geoip==0.5.2
django-haystack==2.4.0
django-model-utils==2.3.1
djangorestframework==3.2.3
Pillow==2.9.0
psycopg2==2.6.1
pysolr==3.3.2
python3-memcached==1.51
pytz==2015.4
regex==2015.7.19
requests==2.7.0
six==1.9.0
sqlparse==0.1.16
uWSGI==2.0.11.1
wheel==0.24.0
```

**Comment by coagulant** [comment]
Does not seem to be related to the library, pls check your app/postgres setup/network/etc.
Feel free to reopen if you disagree )

**Comment by nazariyg** [comment]
Nevermind. Increasing RAM from 768 mb to 2 gb made it through. As a guess only, `IpRange.objects.bulk_create(new_ip_ranges)` was hitting some sort of a bottleneck with RAM. Could be simply due to the fact that system had to be rebooted.
